name: Run code checks
on: [push, pull_request, workflow_dispatch]
jobs:
  fmt:
    runs-on: ubuntu-latest

    container:
      image: timescaledev/rust-builder:ubuntu-1.65

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Verify formatting
        run: cd pgvectorscale && cargo fmt --check

      - name: Check formatting failure
        if: failure()
        run: |
          echo "cargo version is"
          cargo --version


